package com.xjt.mimall.mapper;

import com.xjt.mimall.pojo.MallUser;
import com.xjt.mimall.pojo.MallUserExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface MallUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_user
     *
     * @mbg.generated Mon May 17 16:36:15 GMT+08:00 2021
     */
    long countByExample(MallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_user
     *
     * @mbg.generated Mon May 17 16:36:15 GMT+08:00 2021
     */
    int deleteByExample(MallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_user
     *
     * @mbg.generated Mon May 17 16:36:15 GMT+08:00 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_user
     *
     * @mbg.generated Mon May 17 16:36:15 GMT+08:00 2021
     */
    int insert(MallUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_user
     *
     * @mbg.generated Mon May 17 16:36:15 GMT+08:00 2021
     */
    int insertSelective(MallUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_user
     *
     * @mbg.generated Mon May 17 16:36:15 GMT+08:00 2021
     */
    List<MallUser> selectByExample(MallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_user
     *
     * @mbg.generated Mon May 17 16:36:15 GMT+08:00 2021
     */
    MallUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_user
     *
     * @mbg.generated Mon May 17 16:36:15 GMT+08:00 2021
     */
    int updateByExampleSelective(@Param("record") MallUser record, @Param("example") MallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_user
     *
     * @mbg.generated Mon May 17 16:36:15 GMT+08:00 2021
     */
    int updateByExample(@Param("record") MallUser record, @Param("example") MallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_user
     *
     * @mbg.generated Mon May 17 16:36:15 GMT+08:00 2021
     */
    int updateByPrimaryKeySelective(MallUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_user
     *
     * @mbg.generated Mon May 17 16:36:15 GMT+08:00 2021
     */
    int updateByPrimaryKey(MallUser record);

    /**
     * 根据用户名查询
     * @param username
     * @return
     */
    int countSelectByUsername(String username);

    /**
     * 根据邮箱查询
     * @param email
     * @return
     */
    int countSelectByEmail(String email);
}