package com.xjt.mimall.pojo;

import java.util.Date;

public class MallUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user.id
     *
     * @mbg.generated Mon May 17 16:36:15 GMT+08:00 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user.username
     *
     * @mbg.generated Mon May 17 16:36:15 GMT+08:00 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user.password
     *
     * @mbg.generated Mon May 17 16:36:15 GMT+08:00 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user.email
     *
     * @mbg.generated Mon May 17 16:36:15 GMT+08:00 2021
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user.phone
     *
     * @mbg.generated Mon May 17 16:36:15 GMT+08:00 2021
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user.question
     *
     * @mbg.generated Mon May 17 16:36:15 GMT+08:00 2021
     */
    private String question;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user.answer
     *
     * @mbg.generated Mon May 17 16:36:15 GMT+08:00 2021
     */
    private String answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user.role
     *
     * @mbg.generated Mon May 17 16:36:15 GMT+08:00 2021
     */
    private Integer role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user.create_time
     *
     * @mbg.generated Mon May 17 16:36:15 GMT+08:00 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user.update_time
     *
     * @mbg.generated Mon May 17 16:36:15 GMT+08:00 2021
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user.id
     *
     * @return the value of mall_user.id
     *
     * @mbg.generated Mon May 17 16:36:15 GMT+08:00 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user.id
     *
     * @param id the value for mall_user.id
     *
     * @mbg.generated Mon May 17 16:36:15 GMT+08:00 2021
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user.username
     *
     * @return the value of mall_user.username
     *
     * @mbg.generated Mon May 17 16:36:15 GMT+08:00 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user.username
     *
     * @param username the value for mall_user.username
     *
     * @mbg.generated Mon May 17 16:36:15 GMT+08:00 2021
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user.password
     *
     * @return the value of mall_user.password
     *
     * @mbg.generated Mon May 17 16:36:15 GMT+08:00 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user.password
     *
     * @param password the value for mall_user.password
     *
     * @mbg.generated Mon May 17 16:36:15 GMT+08:00 2021
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user.email
     *
     * @return the value of mall_user.email
     *
     * @mbg.generated Mon May 17 16:36:15 GMT+08:00 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user.email
     *
     * @param email the value for mall_user.email
     *
     * @mbg.generated Mon May 17 16:36:15 GMT+08:00 2021
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user.phone
     *
     * @return the value of mall_user.phone
     *
     * @mbg.generated Mon May 17 16:36:15 GMT+08:00 2021
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user.phone
     *
     * @param phone the value for mall_user.phone
     *
     * @mbg.generated Mon May 17 16:36:15 GMT+08:00 2021
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user.question
     *
     * @return the value of mall_user.question
     *
     * @mbg.generated Mon May 17 16:36:15 GMT+08:00 2021
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user.question
     *
     * @param question the value for mall_user.question
     *
     * @mbg.generated Mon May 17 16:36:15 GMT+08:00 2021
     */
    public void setQuestion(String question) {
        this.question = question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user.answer
     *
     * @return the value of mall_user.answer
     *
     * @mbg.generated Mon May 17 16:36:15 GMT+08:00 2021
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user.answer
     *
     * @param answer the value for mall_user.answer
     *
     * @mbg.generated Mon May 17 16:36:15 GMT+08:00 2021
     */
    public void setAnswer(String answer) {
        this.answer = answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user.role
     *
     * @return the value of mall_user.role
     *
     * @mbg.generated Mon May 17 16:36:15 GMT+08:00 2021
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user.role
     *
     * @param role the value for mall_user.role
     *
     * @mbg.generated Mon May 17 16:36:15 GMT+08:00 2021
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user.create_time
     *
     * @return the value of mall_user.create_time
     *
     * @mbg.generated Mon May 17 16:36:15 GMT+08:00 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user.create_time
     *
     * @param createTime the value for mall_user.create_time
     *
     * @mbg.generated Mon May 17 16:36:15 GMT+08:00 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user.update_time
     *
     * @return the value of mall_user.update_time
     *
     * @mbg.generated Mon May 17 16:36:15 GMT+08:00 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user.update_time
     *
     * @param updateTime the value for mall_user.update_time
     *
     * @mbg.generated Mon May 17 16:36:15 GMT+08:00 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_user
     *
     * @mbg.generated Mon May 17 16:36:15 GMT+08:00 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", email=").append(email);
        sb.append(", phone=").append(phone);
        sb.append(", question=").append(question);
        sb.append(", answer=").append(answer);
        sb.append(", role=").append(role);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}